// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbkveqsyjngimrapaieo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhia3ZlcXN5am5naW1yYXBhaWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjE2ODEsImV4cCI6MjA2NTUzNzY4MX0.8m-cSIjZJqDdfqu88A-f9xlvcAZTC0Z5s7cU5b01hhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);